<?php echo $this->doctype()."\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="<?php echo $this->baseUrl('/images/favicon.png')?>" rel="shortcut icon" />
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headTitle() ?>
</head>

<body>
<a href="<?= $this->url(array('controller' => 'posts', 'action' => 'index'), 'default', true) ?>" >Posts</a> |
<a href="<?= $this->url(array('controller' => 'tags', 'action' => 'index'), 'default', true) ?>" >Tags</a> |
<br/><br/>
<?php echo $this->layout()->content ?>
</body>
</html>